// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package com.zoominfo.drive;

public interface DownloadFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:file_service.DownloadFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();
}
