// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package com.zoominfo.drive;

public interface SignupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:file_service.SignupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
