// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

package com.zoominfo.drive;

public interface UploadFolderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:file_service.UploadFolderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string folderName = 2;</code>
   */
  java.lang.String getFolderName();
  /**
   * <code>string folderName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFolderNameBytes();

  /**
   * <code>repeated .file_service.UploadFileRequest files = 3;</code>
   */
  java.util.List<com.zoominfo.drive.UploadFileRequest> 
      getFilesList();
  /**
   * <code>repeated .file_service.UploadFileRequest files = 3;</code>
   */
  com.zoominfo.drive.UploadFileRequest getFiles(int index);
  /**
   * <code>repeated .file_service.UploadFileRequest files = 3;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .file_service.UploadFileRequest files = 3;</code>
   */
  java.util.List<? extends com.zoominfo.drive.UploadFileRequestOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .file_service.UploadFileRequest files = 3;</code>
   */
  com.zoominfo.drive.UploadFileRequestOrBuilder getFilesOrBuilder(
      int index);
}
